// export * as args from './post.args'
// export * as inputs from './post.inputs'
// export * as model from './post.model'
// export * as mutations from './post.mutations'
// export * as queries from './post.queries'
export * from './post.model.enhance'
export * from './post.resolvers'
export * from './post.reference'
